token = "MTExMTI5OTU2NjcxMzcxMjc2Mg.Gnb8NS.VczVghrDo93WRPEuD8zozf43qP40B7J4iGxFoE"
top-gg-token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwOTgyODAwMzk0ODY4NDkxNzQiLCJib3QiOnRydWUsImlhdCI6MTY4NjMxNjU1NH0.NpsjMDwLOi1Y6vrn3A6GKh9Yrpcmf-F6HOdgBuVBU-g"

# test token:
# "MTExMTI5OTU2NjcxMzcxMjc2Mg.Gnb8NS.VczVghrDo93WRPEuD8zozf43qP40B7J4iGxFoE"
# live token:
# "MTA5ODI4MDAzOTQ4Njg0OTE3NA.GcZ9YQ.byrDuliDirbIUYaP_6iWcv2EBq9q16gdrEXH4g"