name: Update Widget

on:
  push:
    branches:
      - main

jobs:
  update-widget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Add steps to generate/update your widget here
